name: ahm-proptech

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx nest start api-gateway --watch
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api-gateway/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - TSC_WATCHFILE=DynamicPriorityPolling
      - TSC_WATCHDIRECTORY=DynamicPriorityPolling
    volumes:
      - .:/apps
      - /apps/node_modules
    depends_on:
      - auth
      - contact
      - posts
    restart: unless-stopped

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx nest start auth --watch
    ports:
      - '4003:4003'
    env_file:
      - ./apps/auth/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - TSC_WATCHFILE=DynamicPriorityPolling
      - TSC_WATCHDIRECTORY=DynamicPriorityPolling
    volumes:
      - .:/apps
      - /apps/node_modules
    restart: unless-stopped

  contact:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx nest start contact --watch
    ports:
      - '4002:4002'
    env_file:
      - ./apps/contact/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - TSC_WATCHFILE=DynamicPriorityPolling
      - TSC_WATCHDIRECTORY=DynamicPriorityPolling
    volumes:
      - .:/apps
      - /apps/node_modules
    restart: unless-stopped

  posts:
    build:
      context: .
      dockerfile: Dockerfile
    command: npx nest start posts --watch
    ports:
      - '4001:4001'
    env_file:
      - ./apps/posts/.env
    depends_on:
      - elasticsearch
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - TSC_WATCHFILE=DynamicPriorityPolling
      - TSC_WATCHDIRECTORY=DynamicPriorityPolling
    volumes:
      - .:/apps
      - /apps/node_modules
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  elasticsearch-data: