services:
  api-gateway:
    command: npx nest start api-gateway --debug 0.0.0.0:9229 --watch
    ports:
      - '9229:9229'

  analytics:
    command: npx nest start analytics --debug 0.0.0.0:9233 --watch
    ports:
      - '9233:9233'

  auth:
    command: npx nest start auth --debug 0.0.0.0:9232 --watch
    ports:
      - '9232:9232'

  contact:
    command: npx nest start contact --debug 0.0.0.0:9230 --watch
    ports:
      - '9230:9230'

  posts:
    command: npx nest start posts --debug 0.0.0.0:9231 --watch
    ports:
      - '9231:9231'

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://api-gateway:3000
    depends_on:
      - api-gateway
    restart: unless-stopped
